#!/bin/bash

function autoupdate(){
	sudo pacman -Syu archlinux-keyring
	echo "\n\n\t# UPDATING REPOSITORIES AND INTERNAL DATABASE #"
	sudo nmap --script-updatedb; sudo searchsploit -u; sudo updatedb
	echo "\n\n\t# AUTOUPDATE SUCCESSFULLY COMPLETED #"
}
